// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ2b8-tgCERU8EGefwgLwKncR203P1XVU',
    appId: '1:393257855216:web:57035d9c405b001973ba35',
    messagingSenderId: '393257855216',
    projectId: 'fir-flutter-codelab-b15c3',
    authDomain: 'fir-flutter-codelab-b15c3.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-b15c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0SRhcuwU5PutKHkpqaruslBi2fEB6D9A',
    appId: '1:393257855216:android:8bc143837b54839973ba35',
    messagingSenderId: '393257855216',
    projectId: 'fir-flutter-codelab-b15c3',
    storageBucket: 'fir-flutter-codelab-b15c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAErn4XXKVn3T_PUY-qYMgk0_aeqQ04-cI',
    appId: '1:393257855216:ios:fd399be9f085e3e173ba35',
    messagingSenderId: '393257855216',
    projectId: 'fir-flutter-codelab-b15c3',
    storageBucket: 'fir-flutter-codelab-b15c3.appspot.com',
    iosClientId: '393257855216-8us9duvoem12mickv734ogjk3vscno6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAErn4XXKVn3T_PUY-qYMgk0_aeqQ04-cI',
    appId: '1:393257855216:ios:fd399be9f085e3e173ba35',
    messagingSenderId: '393257855216',
    projectId: 'fir-flutter-codelab-b15c3',
    storageBucket: 'fir-flutter-codelab-b15c3.appspot.com',
    iosClientId: '393257855216-8us9duvoem12mickv734ogjk3vscno6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseflutter',
  );
}
